GO
	USE MASTER 
GO
	DROP DATABASE QUANLYTHUVIEN
GO
	CREATE DATABASE QUANLYTHUVIEN
GO
	USE QUANLYTHUVIEN
GO
	CREATE TABLE DAUSACHS(
		ID INT IDENTITY PRIMARY KEY,
		TEN NVARCHAR(MAX),
		TACGIA NVARCHAR(MAX)
	)
GO
	CREATE TABLE DOCGIAS(
		ID INT IDENTITY PRIMARY KEY,
		MADOCGIA VARCHAR(MAX),
		HOTEN NVARCHAR(MAX),
		GIOITINH INT,
		NGAYSINH DATE,
		DIACHI NVARCHAR(MAX)
	)
GO
	CREATE TABLE MUONTRAS(
		ID INT IDENTITY PRIMARY KEY,
		NGAYMUON DATE,
		DOCGIAID INT,
			FOREIGN KEY (DOCGIAID) REFERENCES DOCGIAS(ID),
		DAUSACHID INT,
			FOREIGN KEY (DAUSACHID) REFERENCES DAUSACHS(ID),
		NGAYTRA DATE,
		TRANGTHAI INT, -- 0 : DANG MUON, 1: DA TRA
	)
GO